<?php
    if( !defined("APPNAME") )
    {
        exit;
    }

    define("BUDGET_QUESTION_ORDER_NUMBER", 1);
    define("OS_QUESTION_ORDER_NUMBER", 2);
    define("DISPLAY_DIMENSION_QUESTION_ORDER_NUMBER", 3);
    define("MEMORY_CAPACITY_QUESTION_ORDER_NUMBER", 4);
    define("EXPANDABLE_MEMORY_QUESTION_ORDER_NUMBER", 5);
    define("DUALSIM_QUESTION_ORDER_NUMBER", 6);
    define("5G_QUESTION_ORDER_NUMBER", 7);
    define("LARGE_BATTERY_QUESTION_ORDER_NUMBER", 8);
    define("WIRELESS_CHARGING_QUESTION_ORDER_NUMBER", 9);
